(function (root) {
  'use strict';

  // Density is in g/cm³. Gas values use standard-condition reference density.
  // Values marked estimated are theoretical bulk-density estimates because a
  // macroscopic sample has not been measured.
  const raw = [
    ['H', 'Hydrogen', 0.00008988, 'Gas', false],
    ['He', 'Helium', 0.0001785, 'Gas', false],
    ['Li', 'Lithium', 0.534, 'Solid', false],
    ['Be', 'Beryllium', 1.85, 'Solid', false],
    ['B', 'Boron', 2.37, 'Solid', false],
    ['C', 'Carbon', 2.267, 'Solid', false],
    ['N', 'Nitrogen', 0.0012506, 'Gas', false],
    ['O', 'Oxygen', 0.001429, 'Gas', false],
    ['F', 'Fluorine', 0.001696, 'Gas', false],
    ['Ne', 'Neon', 0.0008999, 'Gas', false],
    ['Na', 'Sodium', 0.968, 'Solid', false],
    ['Mg', 'Magnesium', 1.738, 'Solid', false],
    ['Al', 'Aluminum', 2.7, 'Solid', false],
    ['Si', 'Silicon', 2.329, 'Solid', false],
    ['P', 'Phosphorus', 1.823, 'Solid', false],
    ['S', 'Sulfur', 2.07, 'Solid', false],
    ['Cl', 'Chlorine', 0.003214, 'Gas', false],
    ['Ar', 'Argon', 0.001784, 'Gas', false],
    ['K', 'Potassium', 0.862, 'Solid', false],
    ['Ca', 'Calcium', 1.55, 'Solid', false],
    ['Sc', 'Scandium', 2.985, 'Solid', false],
    ['Ti', 'Titanium', 4.506, 'Solid', false],
    ['V', 'Vanadium', 6.11, 'Solid', false],
    ['Cr', 'Chromium', 7.15, 'Solid', false],
    ['Mn', 'Manganese', 7.21, 'Solid', false],
    ['Fe', 'Iron', 7.874, 'Solid', false],
    ['Co', 'Cobalt', 8.9, 'Solid', false],
    ['Ni', 'Nickel', 8.908, 'Solid', false],
    ['Cu', 'Copper', 8.96, 'Solid', false],
    ['Zn', 'Zinc', 7.14, 'Solid', false],
    ['Ga', 'Gallium', 5.91, 'Solid', false],
    ['Ge', 'Germanium', 5.323, 'Solid', false],
    ['As', 'Arsenic', 5.727, 'Solid', false],
    ['Se', 'Selenium', 4.81, 'Solid', false],
    ['Br', 'Bromine', 3.1028, 'Liquid', false],
    ['Kr', 'Krypton', 0.003733, 'Gas', false],
    ['Rb', 'Rubidium', 1.532, 'Solid', false],
    ['Sr', 'Strontium', 2.64, 'Solid', false],
    ['Y', 'Yttrium', 4.472, 'Solid', false],
    ['Zr', 'Zirconium', 6.52, 'Solid', false],
    ['Nb', 'Niobium', 8.57, 'Solid', false],
    ['Mo', 'Molybdenum', 10.28, 'Solid', false],
    ['Tc', 'Technetium', 11, 'Solid', false],
    ['Ru', 'Ruthenium', 12.37, 'Solid', false],
    ['Rh', 'Rhodium', 12.41, 'Solid', false],
    ['Pd', 'Palladium', 12.023, 'Solid', false],
    ['Ag', 'Silver', 10.49, 'Solid', false],
    ['Cd', 'Cadmium', 8.65, 'Solid', false],
    ['In', 'Indium', 7.31, 'Solid', false],
    ['Sn', 'Tin', 7.287, 'Solid', false],
    ['Sb', 'Antimony', 6.697, 'Solid', false],
    ['Te', 'Tellurium', 6.24, 'Solid', false],
    ['I', 'Iodine', 4.933, 'Solid', false],
    ['Xe', 'Xenon', 0.005894, 'Gas', false],
    ['Cs', 'Cesium', 1.873, 'Solid', false],
    ['Ba', 'Barium', 3.51, 'Solid', false],
    ['La', 'Lanthanum', 6.145, 'Solid', false],
    ['Ce', 'Cerium', 6.77, 'Solid', false],
    ['Pr', 'Praseodymium', 6.77, 'Solid', false],
    ['Nd', 'Neodymium', 7.01, 'Solid', false],
    ['Pm', 'Promethium', 7.26, 'Solid', false],
    ['Sm', 'Samarium', 7.52, 'Solid', false],
    ['Eu', 'Europium', 5.244, 'Solid', false],
    ['Gd', 'Gadolinium', 7.9, 'Solid', false],
    ['Tb', 'Terbium', 8.23, 'Solid', false],
    ['Dy', 'Dysprosium', 8.55, 'Solid', false],
    ['Ho', 'Holmium', 8.795, 'Solid', false],
    ['Er', 'Erbium', 9.066, 'Solid', false],
    ['Tm', 'Thulium', 9.321, 'Solid', false],
    ['Yb', 'Ytterbium', 6.9, 'Solid', false],
    ['Lu', 'Lutetium', 9.841, 'Solid', false],
    ['Hf', 'Hafnium', 13.31, 'Solid', false],
    ['Ta', 'Tantalum', 16.69, 'Solid', false],
    ['W', 'Tungsten', 19.3, 'Solid', false],
    ['Re', 'Rhenium', 21.02, 'Solid', false],
    ['Os', 'Osmium', 22.59, 'Solid', false],
    ['Ir', 'Iridium', 22.56, 'Solid', false],
    ['Pt', 'Platinum', 21.45, 'Solid', false],
    ['Au', 'Gold', 19.3, 'Solid', false],
    ['Hg', 'Mercury', 13.534, 'Liquid', false],
    ['Tl', 'Thallium', 11.85, 'Solid', false],
    ['Pb', 'Lead', 11.34, 'Solid', false],
    ['Bi', 'Bismuth', 9.787, 'Solid', false],
    ['Po', 'Polonium', 9.196, 'Solid', false],
    ['At', 'Astatine', 7, 'Solid', true],
    ['Rn', 'Radon', 0.00973, 'Gas', false],
    ['Fr', 'Francium', 1.87, 'Solid', true],
    ['Ra', 'Radium', 5.5, 'Solid', false],
    ['Ac', 'Actinium', 10, 'Solid', false],
    ['Th', 'Thorium', 11.72, 'Solid', false],
    ['Pa', 'Protactinium', 15.37, 'Solid', false],
    ['U', 'Uranium', 19.1, 'Solid', false],
    ['Np', 'Neptunium', 20.2, 'Solid', false],
    ['Pu', 'Plutonium', 19.7, 'Solid', false],
    ['Am', 'Americium', 13.69, 'Solid', false],
    ['Cm', 'Curium', 13.51, 'Solid', false],
    ['Bk', 'Berkelium', 14.79, 'Solid', false],
    ['Cf', 'Californium', 15.1, 'Solid', false],
    ['Es', 'Einsteinium', 8.84, 'Solid', false],
    ['Fm', 'Fermium', 9.7, 'Solid', true],
    ['Md', 'Mendelevium', 10.3, 'Solid', true],
    ['No', 'Nobelium', 9.9, 'Solid', true],
    ['Lr', 'Lawrencium', 15.6, 'Solid', true],
    ['Rf', 'Rutherfordium', 23.2, 'Solid', true],
    ['Db', 'Dubnium', 29.3, 'Solid', true],
    ['Sg', 'Seaborgium', 35, 'Solid', true],
    ['Bh', 'Bohrium', 37.1, 'Solid', true],
    ['Hs', 'Hassium', 40.7, 'Solid', true],
    ['Mt', 'Meitnerium', 37.4, 'Solid', true],
    ['Ds', 'Darmstadtium', 34.8, 'Solid', true],
    ['Rg', 'Roentgenium', 28.7, 'Solid', true],
    ['Cn', 'Copernicium', 23.7, 'Solid', true],
    ['Nh', 'Nihonium', 16, 'Solid', true],
    ['Fl', 'Flerovium', 14, 'Gas', true],
    ['Mc', 'Moscovium', 13.5, 'Solid', true],
    ['Lv', 'Livermorium', 12.9, 'Solid', true],
    ['Ts', 'Tennessine', 7.17, 'Solid', true],
    ['Og', 'Oganesson', 4.95, 'Gas', true],
  ];

  const elements = Object.freeze(raw.map((item, index) => Object.freeze({
    atomicNumber: index + 1,
    symbol: item[0],
    name: item[1],
    density: item[2],
    phase: item[3],
    estimated: item[4],
  })));

  root.ElementDensityData = elements;
  if (typeof module !== 'undefined' && module.exports) module.exports = elements;
})(typeof window !== 'undefined' ? window : globalThis);
